### ISSUE TITLE
set-env deprecation

### ISSUE THREAD

**Issue by zerg000000** [DeLaGuardo/setup-clojure#15]
repo keep warning about this when I will setup-clojure action

```
The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by DeLaGuardo** [comment]
How do you use the action in your workflow? 
`DeLaGuardo/setup-clojure@master` shouldn't have this warning

**Comment by zerg000000** [comment]
Thanks, the warning disappears after using @master! However, we need a stable build and we are using @2.0 now. Will we have a new release for this?

**Comment by DeLaGuardo** [comment]
Git-based package distribution is not so great in terms of stability (

Here is my personal opinion:

`@2.0` is a reference to a tag attached to the repository. And because those tags can be deleted or moved to a new commit reference you shouldn't consider tagged releases as stable. Another problem of tag-based releases is how hard it is to inspect source code of the action under a tag (much harder to clone repository at tag, github UI is not doing great to show the code at a tag, etc.)

Another option is to refer to commit-sha (via `@sha-string`). I'm not sure that this is anyhow different from tags though.

I'm promising in that action lifetime backward compatibility on a release branch. At the moment this is `master` branch so it should be safe for your workflow to consider this as stable. In the future due to some *potential* breaking changes I will introduce another "stable" branch. Another good reason to stick with a branch-based release is that you can get most recent updates each time your workflow is running.

I'm open for any other opinions and happy to create one more tagged release but wanna try to convince you to use branch-based release first)

**Comment by zerg000000** [comment]
Thanks for the explanation! I am for branch-based release. I may go for the `sha-string` solution!
