### ISSUE TITLE
Support for using `clj`

### ISSUE THREAD

**Issue by RafaeLeal** [DeLaGuardo/setup-clojure#3]
Currently if we use `clj` instead of `clojure`, it will give this error
```
Please install rlwrap for command editing or use "clojure" instead.
make: *** [check] Error 1
Makefile:10: recipe for target 'check' failed
```

**Comment by DeLaGuardo** [comment]
The only reason you want to use `clj` instead of `clojure` is to get better repl experience. In CI/CD workflows there is no need to have it. So I'm not gonna add rlwrap dependency to `clojure-setup` but you still can install it manually. Consider adding the following lines into your workflow: 

```sh
- name: Install rlwrap to have clj command working
  # for ubuntu
  run: apt-get install rlwrap 
  # for mac os x
  run: brew install rlwrap
```

Then `clj` command-line tool will work as expected.

**Comment by RafaeLeal** [comment]
I guess you're right. Maybe would be nice to add this to the readme, it really confused me 🙂

**Comment by DeLaGuardo** [comment]
I think you are right. How about PR? ;)
