### ISSUE TITLE
Support babashka? 

### ISSUE THREAD

**Issue by martinklepsch** [DeLaGuardo/setup-clojure#39]
Would be lovely to have one canonical GH action that supports doing cached installs of different Clojure CLI tools. 

There's a few `setup-babashka` projects, but why not just integrate it here as well, seems like it would be similar to other tools?

**Comment by DeLaGuardo** [comment]
Hi! I see how much babashka offers to clojure community but at the same time I still believe in "unix-way" and would like to encourage others to use dedicated actions (or even shell one-liner because babashka is so amazingly easy to install)
However, there is also caching and versioning problem that can be solved inside of "umbrella" action labelled as "clojure related" so I would like to keep this issue open as an invitation for others willing to contribute via PR.
