### ISSUE TITLE
Version 9.3 doesn't find bb in a monorepo

### ISSUE THREAD

**Issue by dpom** [DeLaGuardo/setup-clojure#67]
It would seem that the DeLaGuardo/setup-clojure action version 9.3 has an issue with monorepo projects.

To highlight this issue I created this project: https://github.com/dpom/test-actions

The actions work without any error in version 7.0 (see branch version7.0) but fail in version 9.3 (main)

**Comment by aviflat** [comment]
@dpom are you sure the problematic factor here is the “monorepo” style repo layout? If so would you mind sharing how you got to that hypothesis?

Is is possible that the problem is related to running `setup-clojure` via a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) instead of in a “regular” step in the jobs?

**Comment by DeLaGuardo** [comment]
this is an issue with composite action. `pre/post` action steps are not available when an action is run from the local directory (the way how composite action works now, I'm not aware why this limitation exists on GH actions side). Sorry for that. Will fix it in the next release planned for this week. Before that, please use 7.0 version.
